# Default values for nginx-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  name: nginx

image:
  repository: nginx
  pullPolicy: IfNotPresent

service:
  name: nginx-service
  type: NodePort
  port: 80
  nodePort: 30004
