apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping-container
        image: alpine
        command: ["ping", "8.8.8.8"]
---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ping
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001