apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongoCredentials.name }}
type: Opaque
data:
  mongodb_user: {{ .Values.mongoCredentials.user }}
  mongodb_pwd: {{ .Values.mongoCredentials.pwd }}
